export const organisationFields = {
  Название: { type: "text", placeholder: "Acme Corp" },
  "Тип отрасли": {
    type: "select",
    options: [
      "Химическая",
      "Производство",
      "Горнодобывающая",
      "Технологии",
      "Энергетика",
    ],
    placeholder: "Выберите отрасль",
  },
  "Координаты местоположения": { type: "text", placeholder: "12.345, -67.890" },
  "Количество сотрудников": { type: "number", placeholder: "500" },
  "Потребление энергии": { type: "number", placeholder: "50000" },
  "Основной источник энергии": {
    type: "select",
    options: [
      "Возобновляемая",
      "Уголь",
      "Природный газ",
      "Ядерная",
      "Солнечная",
    ],
    placeholder: "Выберите источник",
  },
  "Использование воды": { type: "number", placeholder: "10000" },
  "Образование отходов": { type: "number", placeholder: "1000" },
  "Выбросы загрязняющих веществ": { type: "text", placeholder: "CO2, NOx" },
  "Близость к охраняемым территориям": { type: "number", placeholder: "5" },
  "Методы транспортировки": {
    type: "select",
    options: ["Железная дорога", "Дорога", "Море", "Воздух", "Смешанный"],
    placeholder: "Выберите метод",
  },
  "Уровень готовности к бедствиям": {
    type: "select",
    options: ["Низкий", "Средний", "Высокий"],
    placeholder: "Выберите уровень",
  },
  "Соответствие экологическим нормам": {
    type: "select",
    options: ["Да", "Нет"],
    placeholder: "Выберите",
  },
  "Использование опасных материалов": {
    type: "select",
    options: ["Да", "Нет"],
    placeholder: "Выберите",
  },
};

export const facilityFields = {
  Название: { type: "text", placeholder: "Объект А" },
  Тип: {
    type: "select",
    options: [
      "Трансформатор",
      "Осушитель воздуха",
      "Топливный бак",
      "Генератор",
      "Котел",
    ],
    placeholder: "Выберите тип",
  },
  "Координаты местоположения": { type: "text", placeholder: "12.345, -67.890" },
  "Возраст оборудования": { type: "number", placeholder: "5" },
  "Срок службы": { type: "number", placeholder: "20" },
  "Уровень энергоэффективности": { type: "number", placeholder: "85" },
  "Используемое топливо": {
    type: "select",
    options: ["Масло", "Электричество", "Газ", "Уголь", "Биомасса"],
    placeholder: "Выберите топливо",
  },
  "Близость к чувствительным зонам": { type: "number", placeholder: "2" },
  "Уровень выбросов": { type: "text", placeholder: "CO2: 500" },
  "Частота обслуживания": {
    type: "select",
    options: ["Ежемесячно", "Ежеквартально", "Ежегодно"],
    placeholder: "Выберите частоту",
  },
  "Меры безопасности": {
    type: "select",
    options: ["Да", "Нет"],
    placeholder: "Выберите",
  },
  Пожаротушение: {
    type: "select",
    options: ["Да", "Нет"],
    placeholder: "Выберите",
  },
  "Устойчивость к коррозии": {
    type: "select",
    options: ["Да", "Нет"],
    placeholder: "Выберите",
  },
  "Вероятность отказа": {
    type: "select",
    options: ["Низкий", "Средний", "Высокий"],
    placeholder: "Выберите уровень",
  },
  "Риск утечки": {
    type: "select",
    options: ["Низкий", "Средний", "Высокий"],
    placeholder: "Выберите уровень",
  },
};

export const sampleOrganisationData = [
  {
    Name: "Acme Industries",
    "Industry Type": "Производство",
    "Location Coordinates": "55.7558, 37.6176", // Москва, Россия
    "Number of Employees": "1200",
    "Energy Consumption": "75000",
    "Primary Energy Source": "Солнечная",
    "Water Usage": "15000",
    "Waste Generated": "850",
    "Pollutants Emitted": "CO2, NOx",
    "Proximity to Protected Areas": "8",
    "Transportation Methods": "Дорога",
    "Disaster Preparedness Level": "Высокий",
    "Environmental Compliance": "Да",
    "Use of Hazardous Materials": "Нет",
  },
  {
    Name: "Beta Corp",
    "Industry Type": "Технологии",
    "Location Coordinates": "47.9184, 106.9177", // Улан-Батор, Монголия
    "Number of Employees": "500",
    "Energy Consumption": "50000",
    "Primary Energy Source": "Возобновляемая",
    "Water Usage": "10000",
    "Waste Generated": "500",
    "Pollutants Emitted": "CO2",
    "Proximity to Protected Areas": "10",
    "Transportation Methods": "Воздух",
    "Disaster Preparedness Level": "Средний",
    "Environmental Compliance": "Да",
    "Use of Hazardous Materials": "Нет",
  },
  {
    Name: "Gamma Enterprises",
    "Industry Type": "Горнодобывающая",
    "Location Coordinates": "56.8498, 60.6494", // Екатеринбург, Россия
    "Number of Employees": "2000",
    "Energy Consumption": "100000",
    "Primary Energy Source": "Уголь",
    "Water Usage": "20000",
    "Waste Generated": "2000",
    "Pollutants Emitted": "CO2, SO2",
    "Proximity to Protected Areas": "15",
    "Transportation Methods": "Железная дорога",
    "Disaster Preparedness Level": "Низкий",
    "Environmental Compliance": "Нет",
    "Use of Hazardous Materials": "Да",
  },
  {
    Name: "Delta Manufacturing",
    "Industry Type": "Производство",
    "Location Coordinates": "75.8304, 69.0661", // Казань, Россия
    "Number of Employees": "800",
    "Energy Consumption": "60000",
    "Primary Energy Source": "Природный газ",
    "Water Usage": "12000",
    "Waste Generated": "700",
    "Pollutants Emitted": "CO2, NOx",
    "Proximity to Protected Areas": "5",
    "Transportation Methods": "Море",
    "Disaster Preparedness Level": "Высокий",
    "Environmental Compliance": "Да",
    "Use of Hazardous Materials": "Нет",
  },
  {
    Name: "Epsilon Energy",
    "Industry Type": "Энергетика",
    "Location Coordinates": "59.9311, 30.3609", // Санкт-Петербург, Россия
    "Number of Employees": "1500",
    "Energy Consumption": "90000",
    "Primary Energy Source": "Ядерная",
    "Water Usage": "18000",
    "Waste Generated": "1000",
    "Pollutants Emitted": "CO2, NOx, SO2",
    "Proximity to Protected Areas": "12",
    "Transportation Methods": "Смешанный",
    "Disaster Preparedness Level": "Средний",
    "Environmental Compliance": "Да",
    "Use of Hazardous Materials": "Да",
  },
];

export const sampleFacilityData = [
  {
    Name: "Главный генератор",
    Type: "Генератор",
    "Location Coordinates": "60.1699, 24.9384", // Хельсинки, Финляндия
    "Age of Equipment": "3",
    "Service Life": "15",
    "Energy Efficiency Level": "92",
    "Fuel Used": "Газ",
    "Proximity to Sensitive Zones": "1.5",
    "Emission Level": "CO2: 300",
    "Maintenance Frequency": "Ежемесячно",
    "Safety Measures": "Да",
    "Fire Suppression": "Да",
    "Corrosion Resistance": "Да",
    "Failure Potential": "Низкий",
    "Leakage Risk": "Низкий",
  },
  {
    Name: "Резервный трансформатор",
    Type: "Трансформатор",
    "Location Coordinates": "55.8304, 49.0661", // Казань, Россия
    "Age of Equipment": "5",
    "Service Life": "25",
    "Energy Efficiency Level": "88",
    "Fuel Used": "Электричество",
    "Proximity to Sensitive Zones": "2",
    "Emission Level": "CO2: 100",
    "Maintenance Frequency": "Ежеквартально",
    "Safety Measures": "Да",
    "Fire Suppression": "Нет",
    "Corrosion Resistance": "Да",
    "Failure Potential": "Средний",
    "Leakage Risk": "Низкий",
  },
  {
    Name: "Топливный бак",
    Type: "Топливный бак",
    "Location Coordinates": "53.9045, 27.5615", // Минск, Беларусь
    "Age of Equipment": "10",
    "Service Life": "30",
    "Energy Efficiency Level": "75",
    "Fuel Used": "Масло",
    "Proximity to Sensitive Zones": "3",
    "Emission Level": "CO2: 500",
    "Maintenance Frequency": "Ежегодно",
    "Safety Measures": "Нет",
    "Fire Suppression": "Да",
    "Corrosion Resistance": "Нет",
    "Failure Potential": "Высокий",
    "Leakage Risk": "Высокий",
  },
  {
    Name: "Блок осушителя воздуха",
    Type: "Осушитель воздуха",
    "Location Coordinates": "41.7151, 44.8271", // Тбилиси, Грузия
    "Age of Equipment": "2",
    "Service Life": "10",
    "Energy Efficiency Level": "95",
    "Fuel Used": "Электричество",
    "Proximity to Sensitive Zones": "1",
    "Emission Level": "CO2: 50",
    "Maintenance Frequency": "Ежемесячно",
    "Safety Measures": "Да",
    "Fire Suppression": "Нет",
    "Corrosion Resistance": "Да",
    "Failure Potential": "Низкий",
    "Leakage Risk": "Низкий",
  },
  {
    Name: "Котельная установка",
    Type: "Котел",
    "Location Coordinates": "50.4501, 30.5234", // Киев, Украина
    "Age of Equipment": "7",
    "Service Life": "20",
    "Energy Efficiency Level": "85",
    "Fuel Used": "Биомасса",
    "Proximity to Sensitive Zones": "2.5",
    "Emission Level": "CO2: 200",
    "Maintenance Frequency": "Ежеквартально",
    "Safety Measures": "Да",
    "Fire Suppression": "Да",
    "Corrosion Resistance": "Нет",
    "Failure Potential": "Средний",
    "Leakage Risk": "Средний",
  },
];
